debug: true

spring:
  datasource:
    url: jdbc:h2:mem:keycloak;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
keycloak:
  dblock:
    forceUnlock: false
minTimeBetweenRequests: 10
shouldAttachRoute: true
maxErrors: 20
sessionsPerSegment: 64
sessionsPreloadTimeoutInSeconds: 0
cacheThemes: true
lockWaitTimeout: 60
max-detail-length: 50
# used in FreeMarkerUtil
frontendUrl:
adminUrl:
forceBackendUrlToFrontendUrl: false
sslClientCert:
sslCertChainPrefix:
certificateChainLength: 1
theme:
  cacheTemplates: true
socket-timeout-millis: -1
establish-connection-timeout-millis: 1
max-pooled-per-route: 64
connection-pool-size: 128
connection-ttl-millis: -1
max-connection-idle-time-millis: 900000
disable-cookies: true
client-keystore:
client-keystore-password:
client-key-password:
proxy-mappings:
disable-trust-manager:
include-events:
exclude-events:
success-level: debug
error-level: warn
knownProtocols:
dir:
file:
password:
hostname-verification-policy:
keyResolvers: